//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitacionesXHotel
    {
        public int id_relacion { get; set; }
        public Nullable<int> id_hotel { get; set; }
        public Nullable<int> codigo_habitacion { get; set; }
        public Nullable<bool> estado_habitacion { get; set; }
    
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Hoteles Hoteles { get; set; }
    }
}
