//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservaciones()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int id_reservacion { get; set; }
        public int precio_reservacion { get; set; }
        public System.DateTime fecha_entrada_reservacion { get; set; }
        public System.DateTime fecha_salida_reservacion { get; set; }
        public string nombre_reservacion { get; set; }
        public Nullable<int> hotel_reservacion { get; set; }
        public Nullable<int> habitacion_reservacion { get; set; }
        public Nullable<int> cliente_reservacion { get; set; }
        public Nullable<int> agencia_reservacion { get; set; }
        public string descuento_reservacion { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Descuentos Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Hoteles Hoteles { get; set; }
    }
}
